fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    host: "git://github.com/puppetlabs/puppetlabs/puppetlabs-host_core.git"
  symlinks:
    network: "#{source_dir}"
