name          'example42-network'
version '3.1.4'
source        'https://github.com/example42/puppet-network'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module installs and configures networking on Debian RedHat and Suse'
description   'This module installs and configures networking on Debian RedHat and Suse. Based of stdmod/puppet-skeleton-standard 0.0.3.'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'puppetlabs/concat'
dependency    'example42/stdmod'
