name          'example42-network'
version       '0.0.3'
source        'UNKNOWN'
author        'example42'
license       'Apache License, Version 2.0'
summary       'This module installs and manages network'
description   'UNKNOWN. Based of stdmod/puppet-skeleton-standard 0.0.3.'
project_page  'UNKNOWN'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
